spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chess_dev
    username: username
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

frontend:
  url : "http://localhost:3000"