spring:
  datasource:
    url: jdbc:mysql://${MYSQLUSER}:${MYSQLPASSWORD}@${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: root
    password: '${MYSQLPASSWORD}'
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: '${CLIENT_ID_GOOGLE}'
            clientSecret: '${CLIENT_SECRET_GOOGLE}'
          github:
            clientId: ${CLIENT_ID_GITHUB}
            clientSecret: ${CLIENT_SECRET_GITHUB}
frontend:
  url : '${FRONTEND}'

encryption:
  secret: '${KEY}'