
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: http://localhost:3000
        allowed-methods: GET ,POST

spring:
  devtools:
    livereload:
      enabled: false
  profiles:
    active: prod



