spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASS}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

frontend:
  url : ${FRONTEND_URL}

encryption:
  secret: ${ENCRYPTION_KEY}