spring:
  devtools:
    livereload:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/chess_dev
    username: root
    password: password

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

management:
  endpoints:
    config-props:
      keys-to-sanitize: password
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: http://localhost:3000
        allowed-methods: GET ,POST